More multi-thread support
rust-av/av-metrics pull request #168
Opened 2020-10-02 23:03 UTC by lu-zero

According to hyperfine  4.03 ± 0.01 times faster on a 20-hw-threads machine.

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `./av-metrics-tool-mt ~/Samples/Bosphorus_1920x1080_120fps_420_8bit_YUV.y4m /tmp/out.y4m` | 111.635 ± 0.260 | 111.451 | 111.819 | 1.00 |
| `./av-metrics-tool-no-mt ~/Samples/Bosphorus_1920x1080_120fps_420_8bit_YUV.y4m /tmp/out.y4m` | 450.062 ± 0.396 | 449.783 | 450.342 | 4.03 ± 0.01 |

2020-10-03 01:47 UTC, shssoichiro approved these changes

2020-10-03 02:03 UTC, shssoichiro requested changes
Actually it turns out the tests are unhappy... I can look into it unless you have time sooner.

2020-10-03 08:19 UTC, lu-zero commented
I should had read with more attention what `while_some()` does.

2020-10-03 22:19 UTC, shssoichiro commented
It seems there's some capability for the tests to go into an infinite loop. But it seems to not happen every run. I've only seen it in CI. In this case, it happened on Windows but not on Ubuntu.

2020-10-04 08:06 UTC, lu-zero commented
it is probably a quasi-deadlock, I do not see how it could enter an infinite loop but I can imagine the situation in which it starts processing more frames while there is pending work to be done to complete one.

2020-10-04 10:43 UTC, lu-zero commented
I tried to reproduce the problem with a small [testcase](https://gist.github.com/lu-zero/6774feae6e57369140b38005fe6f999f), when the pool is 1 threads it deadlocks apparently.

2020-10-04 11:28 UTC, lu-zero commented
Now it seems working as intended even when 1 single thread is available

2020-10-04 16:00 UTC, shssoichiro approved these changes

2020-10-04 17:03 UTC, merged